version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"
    ignore:
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
