version: "2"
run:
  build-tags:
    - e2e
  modules-download-mode: vendor
  issues-exit-code: 1
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - unconvert
    - usestdlibvars
    - usetesting
    - whitespace
    - zerologlint
  disable:
    - cyclop
    - dupl
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - ireturn
    - lll
    - mnd
    - nestif
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - testpackage
    - tparallel
    - unparam
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: 'replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil'
            - pkg: github.com/ghodss/yaml
              desc: use sigs.k8s.io/yaml instead, to be consistent
    errcheck:
      exclude-functions:
        - flag.Set
        - os.Setenv
        - logger.Sync
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Closer).Close
        - updateConfigMap
    gomodguard:
      blocked:
        modules:
          - github.com/ghodss/yaml:
              recommendations:
                - sigs.k8s.io/yaml
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: main\.go
      - linters:
          - dogsled
          - errcheck
          - goconst
          - gosec
          - ineffassign
          - maintidx
        path: _test\.go
    paths:
      - .*/zz_generated.deepcopy.go
      - pkg/apis/pipeline/v1beta1/openapi_generated.go
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*/zz_generated.deepcopy.go
      - pkg/apis/pipeline/v1beta1/openapi_generated.go
      - vendor
      - third_party$
      - builtin$
      - examples$
