apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-mcp-server
  namespace: tekton-mcp
  labels:
    app.kubernetes.io/name: tekton-mcp
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-mcp
    app.kubernetes.io/managed-by: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-mcp
      app.kubernetes.io/component: mcp-server
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: tekton-mcp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tekton-mcp
        app.kubernetes.io/component: mcp-server
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-mcp
        app.kubernetes.io/managed-by: tekton-pipelines
    spec:
      serviceAccountName: tekton-mcp-server
      containers:
      - name: tekton-mcp-server
        image: ko://github.com/tektoncd/mcp-server/cmd/tekton-mcp-server
        ports:
        - name: http
          containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - all
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
