apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-mcp-server
  namespace: tekton-mcp
  labels:
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-mcp
