# Copyright 2024 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-mcp-server
  namespace: tekton-mcp-server
  labels:
    app.kubernetes.io/name: tekton-mcp-server
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/part-of: tekton-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tekton-mcp-server
      app.kubernetes.io/component: mcp-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tekton-mcp-server
        app.kubernetes.io/component: mcp-server
        app.kubernetes.io/part-of: tekton-mcp
    spec:
      serviceAccountName: tekton-mcp-server
      containers:
      - name: mcp-server
        image: ko://github.com/tektoncd/mcp-server/cmd/tekton-mcp-server
        args:
          - "-transport"
          - "http"
          - "-address"
          - ":3000"
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_MIN_VERSION
          value: "1.25.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault