apiVersion: v1
kind: Service
metadata:
  name: tekton-mcp-server
  namespace: tekton-mcp
  labels:
    app.kubernetes.io/name: tekton-mcp
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-mcp
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/name: tekton-mcp
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-mcp
